version: '3.4'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=notSoSafePassword
    ports:
      - "27017:27017"
    command: mongod --auth    
    networks:
      - binary-diff-dev
