version: '3.4'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: notSoSafePassword
    ports:
      - '27017:27017'
    command: mongod --auth
    volumes:
      - mongo-data:/var/data/mongo
    networks:
      - binary-diff-dev

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: notSoSafePassword
      POSTGRES_DB: BinaryDiffResultDb
    volumes:
      - postgres-data:/var/data/postgres
    ports:
      - 5432:5432
    networks:
      - binary-diff-dev

  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine
    restart: always
    hostname: rabbitmq-host
    volumes:
      - rabbitmq-data:/var/data/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - binary-diff-dev
      
volumes:
  mongo-data:
  postgres-data:
  rabbitmq-data: